version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: papermark
      POSTGRES_PASSWORD: papermark_password
      POSTGRES_DB: papermark_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
